### ISSUE TITLE
Basic Chat moves my chat windows way off the screen

### ISSUE THREAD

**Issue by akidraham** [GryllsAddons/ShaguTweaks-Mods#1]
So i used the Basic Chat mods and it moved my chat window wayyyyy off screen. I'm playing on a laptop with 1366x768 screen, and my in game resolution i set it to 1280x720 with UI Scale set on 0.81

so i deactivated the basic chat mods and had to redo my layout-cache.txt inside the Game Folder/WTF/Account/AccountName/RealmName/CharacterName/layout-cache.txt 

![WoW_TbEE53squb](https://user-images.githubusercontent.com/102669236/187687682-c8ce4f22-8d43-4639-831a-ab83375c757b.jpg)

and i really love this mods, especially the center ui 🔥

**Comment by GryllsAddons** [comment]
Thanks for the feedback! I'll do some testing with more resolutions and can hopefully have a solution for you soon!

**Comment by GryllsAddons** [comment]
I've just uploaded a new version of basic chat please let me know if this fixes the issue!

Apologies that you had to reset the layout-cache, if something does go wrong again you might be able to reset the chat boxes in-game by using the in game simple chat option:

1. Uncheck Basic Chat from Advanced Options > Okay
2. Interface Options > Simple Chat > Check > Okay
3. Interface Options > Simple Chat > Uncheck > Okay

**Comment by akidraham** [comment]
Hi, this is my chat window looks like after i updated the basic-chat module
![WoW_q37OCLOkRa](https://user-images.githubusercontent.com/102669236/187813728-336ee135-5d72-4c47-85a2-aff03ec575e3.png)

It's still slightly off

**Comment by GryllsAddons** [comment]
That's great the boxes haven't gone off the screen! 

Currently the mod moves uses the size of the action buttons and the experience bar as a reference to position the chat boxes. Lines 14 and 15 control the x and y position of the boxes (I've tried to find a way that would work with all resolutions - there may be a better way!). You can increase the value of line 15 for the height or once the chat is setup as you say you can disable and move the boxes as you like! 

With this mod the intention is just a quick way to setup chat boxes (like you have in pfUI) and you can move them later if needed.

**Comment by akidraham** [comment]
Thank you, i love you my man, apparently indeed Diablo Orbs addon messed with the module

this is without Diablo Orbs addon
![WoW_sDzZAplqrB](https://user-images.githubusercontent.com/102669236/187945892-b8629f38-1e94-4072-a28c-d38ac30ab3a2.jpg)

And this with the Diablo Orbs addon
![WoW_ew8Ydc48tG](https://user-images.githubusercontent.com/102669236/187946516-c1181550-b76c-4126-8cad-92576de5d7e8.jpg)

**Comment by GryllsAddons** [comment]
Fantastic! I'm glad that's helped! Hope you enjoy and please continue to give any feedback it's really helpful!
