### ISSUE TITLE
Make mouseover cast show icon cooldown; allow interface resize

### ISSUE THREAD

**Issue by ibuk27** [GryllsAddons/ShaguTweaks-Mods#10]
Mouseover cast via /stcast macro does not show icon cooldown in actionbar. Perhaps add the following?:

/script if nil then CastSpellByName("SPELLNAME"); end

Also, it would be nice to have an option to resize the interface window. I have a small monitor a use big uiscaling, so the interface buttons  are out of reach.

Thanks for a great addon.

**Comment by GryllsAddons** [comment]
Thanks for raising this issue!

I have added the improved advanced options mod back (this was removed with the recent update to the ShaguTweaks interface making it a scrolling list). If you redownload the addon it should automatically be enabled and you can drag the window or rescale the window by using ctrl + mousewheel. If you ctrl and mousewheel at the top of the window it's a bit easier! 

For the cooldown issue I believe you have to add the script as part of the macro rather than in the stcast code.

Hope this helps!

**Comment by ibuk27** [comment]
Thanks for the reply and the fix for improved advanced options!
I'm not savvy in that respect, so I was wondering if you could add show icon cooldown directly into the stcast code. It's possible to to do so adding the script to the macro, but most people don't know about this. The stcast option becomes almost unviable without the cooldown icon (image being a paladin and having no information on cooldowns for lay on hands, blessings, divine intervention, etc.).

**Comment by GryllsAddons** [comment]
I've looked at how pfUI does this and have created a new mod called "Macro Icons & Cooldowns". With this enabled the action buttons should be able to get the spell icon and cooldown (cooldown shadow) for macros using /stcast . You will also need the Cooldown Numbers mod enabled for numeric cooldowns. I haven't been able to fully test the mod for all stances and forms please let me know if you encounter any issues!

**Comment by ibuk27** [comment]
Wow, that's great! "Macro Icons & Cooldowns" is working perfectly with the normal /cast command. With the /stcast command it's showing cooldown shadow, but it's unable to get other information, like spell out of range or out of mana. Almost there, I'd say :) Thanks again for this
![stcast](https://user-images.githubusercontent.com/126533150/222958264-58b9b0cf-58e7-42d5-a19a-2ad71b74eacb.png)

**Comment by GryllsAddons** [comment]
I'll try to find a way to do this as a future improvement - not as easy as I thought it would be!

**Comment by GryllsAddons** [comment]
I've tried a number of things not sure it is possible to add the range and mana through the addon code with the default action buttons. I'll close this issue but keep this in mind if I come across a way to do this in the future. The current solution is to add "/script if nil then CastSpellByName("SPELLNAME"); end" to the macro.
