### ISSUE TITLE
Missing Unit Frame Values & Show Unexplored Areas Option

### ISSUE THREAD

**Issue by DigitalLaborer** [GryllsAddons/ShaguTweaks-Mods#12]
GryllsUnitFrames' addon page on GitHub it says that "Notice: Many of the features of this addon or a superior and maintained version is included in ShaguTweaks-Mods" but party and target of target values options aren't included in ShaguTweaks-Mods and they're only available in GryllsUnitFrames. Also, one thing that I think that is missing from the ShaguTweaks-Mods addon is a "Show Unexplored Areas" option on the map. I think these features should be added to ShaguTweaks-Mods. That's all I have to say, thank you so much in advance.

**Comment by DigitalLaborer** [comment]
Any update on this?

**Comment by GryllsAddons** [comment]
I've added a "Real Health Numbers Extended" mod which extends the functionality of "Real Health Numbers" to add tot and party numbers alongside a WorldMap Reveal mod (from pfUI) to reveal unexplored areas. Please let me know if you encounter any issues.

**Comment by DigitalLaborer** [comment]
Everything works as intended so far, thank you so much for taking notice of my suggestions!
