### ISSUE TITLE
Improved Interface Options Option Doesn't Work When Central Interaction Windows Option is Also Enabled

### ISSUE THREAD

**Issue by DigitalLaborer** [GryllsAddons/ShaguTweaks-Mods#13]
"Improved Interface Options" option makes the interface options' text disappear and it makes only the boxes remain but the settings unchangeable when "Central Interaction Windows" option is enabled, so they don't work together. Hopefully this gets fixed, thanks in advance.

![image](https://user-images.githubusercontent.com/71216325/234137116-3f1b9ef6-4eff-41b4-ae8c-3727c9f63ef2.png)

**Comment by GryllsAddons** [comment]
Thank you good catch! It seems like this was the only window affected. I've updated the mod hopefully you should now be able to use the interface options again!
