### ISSUE TITLE
LilSparkysWorkshop incompatibility with Rarity Extended / Glow options?

### ISSUE THREAD

**Issue by AngryMustache** [GryllsAddons/ShaguTweaks-mods#18]
Just bringing to your attention there seems to be some incompatibility between these options and LSW being installed.

Wasn't really sure if it was really those options at fault or LSW since it only happens with LSW installed and those options checked. The base Item Rarity Borders from tweaks does not cause any issues.

I have attached the error messages below, if it is of any use.

![WoW_2023-06-12 10-21-44](https://github.com/GryllsAddons/ShaguTweaks-mods/assets/16059310/02648bd1-0885-467a-8382-5d4af40b2df9)
![WoW_2023-06-12 10-25-32](https://github.com/GryllsAddons/ShaguTweaks-mods/assets/16059310/166d6682-9519-4f08-8fe3-4e2a7411b273)

**Comment by AngryMustache** [comment]
Yeah I was getting both errors before, both with and without ATSW in combination with LSW. Now it seems both errors disappear when LSW and ATSW are used together.

I still get the item-colors-glow.lua line 78 and item-colors-extended.lua line 26 error same as above if using the stock tradeskill window with LSW only, and it only happens on closing the window, not opening it. Testing it with tailoring.

Maybe it would be best just to disable LSW, or hide errors as it's probably somewhat outside of the scope of your project to try to work around what I assume is code on LSW's end being at fault. 

Seems like something specific LSW is doing is causing these conflicts, as they disappear when it's not loaded, with or without using ATSW, on my machine.

**Comment by GryllsAddons** [comment]
Thanks your right I checked again with only ATSW and no errors but does have error when ATSW and LSW are enabled together. I've changed it to look for LSW instead of ATSW which should prevent the error.

**Comment by GryllsAddons** [comment]
Thanks, it's a bit of a strange on as the function that's causing the error shouldn't be called when for crafting or tradeskills. I can't seem to recreate this unfortunately - does the error still occur with only shagutweaks+mods and LSW enabled or are there any other addons enabled? I've updated the mods again which may help.

**Comment by AngryMustache** [comment]
Yeah I had some other addons enabled, but nothing else that interact with the tradeskill/profession windows. Just a few things like aux / bettercharacterstats / cartographer / succ bag / fishingbuddy / hcwarn / healcomm / unitscan / pfquest.

Regardless it seems the latest push has fixed it, as now all of the errors are gone. Thanks!

**Comment by GryllsAddons** [comment]
Ah fantastic! thanks please let me know if you have any further issues!
