### ISSUE TITLE
frame rate overlaps with bg control ui

### ISSUE THREAD

**Issue by burner1024** [GryllsAddons/ShaguTweaks-mods#19]
Hard to use BG ui like this. Maybe it down a little? Or somewhere else.
![Captura desde 2023-06-15 10-21-37](https://github.com/GryllsAddons/ShaguTweaks-mods/assets/1279852/803cffb6-84b4-4fa5-aa31-6b6f0115e15b)

**Comment by burner1024** [comment]
thanks!

**Comment by Sattva-108** [comment]
Hi im playing tbc and made some changes. 
What do you think of my design? I just didn't feel like fps and ms overlapping the minimap at all. 
Wonder why can it be bad to have fps/ms outside? Or just user preference it is?

![Wow_TnSmat7wex](https://github.com/GryllsAddons/ShaguTweaks-mods/assets/74269253/bcb7329b-af7f-43c3-9ca8-7770828d29d1)

**Comment by burner1024** [comment]
I did the same, actually.
![Captura desde 2023-06-18 15-37-31](https://github.com/GryllsAddons/ShaguTweaks-mods/assets/1279852/6ece0a97-fb45-4ee8-b8b6-6da72fd51991)

**Comment by GryllsAddons** [comment]
Thanks for the feedback the current position is mainly to have it side by side with the existing clock option. It could position itself below the map if the clock is not enabled perhaps.
