### ISSUE TITLE
Hide Combat Tooltip modules breaks roid macro mouseover

### ISSUE THREAD

**Issue by akidraham** [GryllsAddons/ShaguTweaks-Mods#2]
As the title says, Hide Combat Tooltip modules breaks roid macro mouseover, if i turn the modules off i can use my mouseover macro again. 

I can use mouseover again if I press Shift to display the tooltips again or I disable the module.

active Addons:
[NotGrid](https://github.com/laytya/NotGrid)
ShaguTweaks
[RoidMacro](https://github.com/DennisWG/Roid-Macros)
[ClassicMouseover](https://github.com/satan666/LazySpell)

my macro:
/script if nil then CastSpellByName("Healing Touch(Rank 4)"); end
/cast [@mouseover help hp<99] Healing Touch(Rank 4); [@focus hp<99] Healing Touch(Rank 4); [target] Healing Touch(Rank 4)
END

**Comment by GryllsAddons** [comment]
Thanks for raising this issue, I believe this may be caused by how the mod is hiding the tooltip. I've uploaded a new version which uses a different method to hide it. I will do some further testing to check but i'm hoping this will resolve the issue!

**Comment by akidraham** [comment]
> Thanks for raising this issue, I believe this may be caused by how the mod is hiding the tooltip. I've uploaded a new version which uses a different method to hide it. I will do some further testing to check but i'm hoping this will resolve the issue!

Thank you thank you thank you, as to my current limited testing it worked great now, i'll post anything if i have further issue with it

**Comment by GryllsAddons** [comment]
That's great I'm glad to hear it's working again! Please do open a new issue if you do find any further issues!
