### ISSUE TITLE
[REQUEST] TBC version

### ISSUE THREAD

**Issue by Nakris** [GryllsAddons/ShaguTweaks-mods#20]
Hello!
Can you make this addon work with ShaguTweaks 2.4.3 please ?

**Comment by GryllsAddons** [comment]
Thanks for raising this. Unfortunately I don't play TBC and I'm unfamiliar with API changes after 1.12 so I'm unable to guarantee the mods will work on this version.

You can try changing the code below for the mod you are interested in to enable it for TBC you may have some success.
`expansions = { ["vanilla"] = true, ["tbc"] = true },`

**Comment by Sattva-108** [comment]
@Nakris 
i did already do some job for 2.4.3, and my mate @Macumbafeh did help me too. 
https://github.com/Sattva-108/ShaguTweaks-Mods-TBC-2.4.3

though it needs a lot of job still!
first thing i would do is probably fix the way improvedcastbar made in my fork, as it was Macumba idea to add libs and make that castbar, which i think is no better than Grylls one ! :)

May be i will come back to that addon sometime... For now working on another projects.
