### ISSUE TITLE
Target frame buff cap

### ISSUE THREAD

**Issue by ibuk27** [GryllsAddons/ShaguTweaks-mods#21]
Any plans to expand cap on number of buffs showing on target frame? Default Ui for vanilla client has a limit of 5 and I can't find any option in shagutweaks mods to increase this.

**Comment by GryllsAddons** [comment]
Thanks, it might be something to look into!

In the meantime the addon below should show the extra buffs/debuffs:

https://github.com/ZiiMs/TargetFrameBuff

Hope this helps!

**Comment by ibuk27** [comment]
Thanks a lot for the reply. The problem with the addon you linked is that ToT frame covers buff icons:

![buffs](https://github.com/GryllsAddons/ShaguTweaks-mods/assets/126533150/35db9f7f-eaf4-4fc8-aed9-32baaf86aeb7)

Looking forward to a working equivalent for shagu mods. Keep up the good work!

**Comment by GryllsAddons** [comment]
I've added a mod for this based on TargetFrameBuff, it should resolve the ToT issue (it will show rows of 4 when you have a ToT and 5 is no ToT). Please let me know if you find any issues!

![image](https://github.com/GryllsAddons/ShaguTweaks-mods/assets/107083057/4a63b2c7-8824-4348-a0aa-e2d59df2e099)

**Comment by ibuk27** [comment]
Great work! Thanks a lot for this one!

**Comment by WuVenus** [comment]
How do I uncolor the BUFF box
