### ISSUE TITLE
 vanilla default nameplate overlap 

### ISSUE THREAD

**Issue by WuVenus** [GryllsAddons/ShaguTweaks-mods#22]
vanilla default nameplate overlap 
It was a good decision

**Comment by GryllsAddons** [comment]
Thanks, perhaps something that could be explored. The default nameplates are quite limited as to what you can do with them - you might have some luck using [ShaguPlates ](https://github.com/shagu/ShaguPlates) as it has a feature to allow overlapping plates (along with other good enhancements).

**Comment by GryllsAddons** [comment]
I'm not sure if this is possible with the default plates (or it's beyond my knowledge) - this might be one to suggest to Shagu instead.
