### ISSUE TITLE
I think you should add backpack items to organize

### ISSUE THREAD

**Issue by WuVenus** [GryllsAddons/ShaguTweaks-mods#26]
https://www.curseforge.com/wow/addons/tdpack2
Maybe put this in 1.12.1 which I think would be perfect,
He's an individual Organize things!

**Comment by GryllsAddons** [comment]
Thanks for the feedback! 

This kind of addition would be a bit more than a small tweak but you may want to look at [SUCC-bag](https://github.com/GryllsAddons/SUCC-bag) which is a simple one bag inventory. 

You can use [Clean_Up](https://github.com/GryllsAddons/Clean_Up) with SUCC-bag to add a button for sorting and organising your inventory.

Hope this helps!
