### ISSUE TITLE
Minor bugs to UI and chat

### ISSUE THREAD

**Issue by Volkyte** [GryllsAddons/ShaguTweaks-Mods#4]
![Immagine 2022-11-15 094157](https://user-images.githubusercontent.com/16918614/201878024-a855c71c-9bb5-4635-9816-6123881ee3b2.jpg)

Pet frames not coloured by happiness, in fact they remane the same. Chat tweaks always make you have the "arrow" when you change chat tabs every time. (not hidden as per addon description)

**Comment by GryllsAddons** [comment]
Thanks for raising this. I've uploaded new versions of the mods hopefully they should help. The bottom arrow chat button should no longer be shown when changing tabs. I've also attempted to fix the pet happiness however I don't have access to a hunter atm to test - I'll test this properly soon please let me know how you get on.

**Comment by GryllsAddons** [comment]
Pet Health Color mod which colors the pet health bar has been replaced Pet Name Happiness mod which colors the pet name.
