### ISSUE TITLE
Change color of powerbar?

### ISSUE THREAD

**Issue by Ayzkronos** [GryllsAddons/ShaguTweaks-Mods#5]
https://raw.githubusercontent.com/GryllsAddons/AddonPreviews/main/GryllsUnitFrames/GUF1.png
I tried to download the gryllsUnitFrames where the screenshot is from, but while the other features described in the addon works - it does not make the manabar white like on the screenshots, and there seems to be no function inside the addon that can change it. It can change the text on the manabar to white, but not the bar itself.

It said in that github that the addon is a part of the shagutweaksmods now, so thats why im posting here.
Maybe im doing something wrong, otherwise i beg you to add this feature :) thank you

**Comment by GryllsAddons** [comment]
Thanks for the request, the GryllsUnitFrames addon allowed you to colour the text or hide the text under certain conditions.

To clarify, you would like to find a way to change the color of the manabar to white? e.g. mana/rage/energy would show as a white bar instead of blue/red/yellow?

**Comment by Ayzkronos** [comment]
Correct. However energy and rage have colors that are easily seen, it would be nice to keep the colors for those. Only in the case of mana is the color an issue. Dark blue on dark background dont work. So i would like the powerbar to be white in the case of mana. White/yellow/red instead of dark blue/yellow/red.

**Comment by GryllsAddons** [comment]
I've added a mod which should change the mana color to white. Please download and install the addon again and it should appear in the "Unit Frames" section under "Unit Frames White Mana".

**Comment by Ayzkronos** [comment]
It works! amazing feature thank you

**Comment by GryllsAddons** [comment]
I've just uploaded a new version of this which should be more efficient.
