### ISSUE TITLE
Can't save changes

### ISSUE THREAD

**Issue by mikefirefly** [GryllsAddons/ShaguTweaks-Mods#6]
Options window is so big that there is no way to click Okay button so I'm unable to save changes.

![image](https://user-images.githubusercontent.com/13250690/213500127-be74108f-50ec-4052-9e25-0ed7514dfb1a.png)

**Comment by GryllsAddons** [comment]
Thanks for raising this, the window not fitting on the screen is a known issue. I've included the "Improved Advanced Options" mod to attempt to correct this by rescaling the window. In this case using the current UI scale the window is still too big. 

I've previously submitted a feature request for ShaguTweaks to be able to fit a larger amount of mods [here](https://github.com/shagu/ShaguTweaks/issues/19) so hopefully this might be added in the future.

One solution other than changing the UI scale would be to change the Improved Advanced Options window scaling value by opening the Lua file located in "\Interface\AddOns\ShaguTweaks\mods\improved-advanced-options.lua" and changing line 11 "AdvancedSettingsGUI:SetScale(0.88)" to a smaller value such as "AdvancedSettingsGUI:SetScale(0.6)". This should rescale the window so the bottom bit of the window is accessible.

Hope this helps!

**Comment by GryllsAddons** [comment]
An update to the Improved Advanced Options mod now allows moving and scaling which should finally resolve until additional columns can be implemented.

**Comment by shagu** [comment]
The Advanced Options do now scroll with the latest version. (https://github.com/shagu/ShaguTweaks/pull/33)
