### ISSUE TITLE
Improved Advanced Options causes actionbars to show even if hidden in the interface settings

### ISSUE THREAD

**Issue by Arcose** [GryllsAddons/ShaguTweaks-Mods#8]
Hello,

Currently if the "Improved Advanced Options" settings is set in the "Advanced Options" menu, all of your actionbars appear when you leave the menu, even if they were all disabled in the "Interface Options." This currently can cause the issue shown in the image below, if you also have "Reduced Actionbar Size" enabled, enter and leave the "Advanced Options" menu, and then enter and press escape to leave the "Interface Options" menu. The image is also taken with "Always Show Actionbars." And even without "Reduced Actionbar Size" enabled, the actionbars still forcibly appear when the menu is closed and only disappear when the "Interface Options" is entered and exited or the UI is reloaded.

Floating Shapeshift Bar and Misaligned Bags:
![Invisible bars](https://user-images.githubusercontent.com/28908448/214982668-fae5897d-43f8-42f3-95ff-9a76c4041609.png)

I suspect that the issue is being caused by the show() function by choosing to Show() all actionbars even if they were hidden prior to opening up the "Advanced Options" menu. I'm not sure if it would be possible to save the prior state of the actionbars before hiding them so that their correct state could be restored when the menu is closed.

Located in: improved-advanced-options.lua
```
  local function hide()
    PlayerFrame:SetAlpha(0)
    TargetFrame:SetAlpha(0)
    PetActionBarFrame:Hide()
    MultiBarBottomRight:Hide()
    MultiBarBottomLeft:Hide()
    MultiBarRight:Hide()
    MultiBarLeft:Hide()
    MainMenuBar:Hide()
  end

  local function show()
    PlayerFrame:SetAlpha(1)
    TargetFrame:SetAlpha(1)
    PetActionBarFrame:Show()
    MultiBarBottomRight:Show()
    MultiBarBottomLeft:Show()
    MultiBarRight:Show()
    MultiBarLeft:Show()
    MainMenuBar:Show()
  end
```

**Comment by GryllsAddons** [comment]
I added this code to try to allow a bigger mods window. I've now removed this code hopefully Shagu will be able to implement a way of adding more columns to the main window instead in the future.
