### ISSUE TITLE
"Central UI" makes minimap bug out.

### ISSUE THREAD

**Issue by gebbebebbebebr** [GryllsAddons/ShaguTweaks-Mods#9]
Video of the issue https://files.catbox.moe/mq6x31.mp4

**Comment by gebbebebbebebr** [comment]
commenting out line 37 to 47 in mods/central-ui.lua fixed the issue for me. https://github.com/GryllsAddons/ShaguTweaks-Mods/blob/21f1b266da2a2252b838365fd8288e95f8e6490d/ShaguTweaks/mods/central-ui.lua#L37

**Comment by GryllsAddons** [comment]
Thank you for the video. I've amended the positioning of the minimap in the code hopefully this shouldn't happen anymore!
